trigger:
  branches:
    exclude:
      - main
      - QA

resources:
  repositories:
    - repository: self
      ref: main
      pipeline: CI-storyTest.yml
      source: azure/CI-storyTest.yml

stages:
  - stage: StoryTest
    jobs:
      - job: Run_Story_Test
        displayName: 'Run Story Test'
        steps:
          - template: azure/CI-storyTest.yml

  - stage: RegressionTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/QA'))
    jobs:
      - job: Run_Regression_Test
        displayName: 'Run Regression Test'
        steps:
          - template: azure/CI-regressionTest.yml